### ISSUE TITLE
Not responding window

### ISSUE THREAD

**Issue by BudkoIlya** [TeamREPENTOGON/REPENTOGON#195]
Removed all mods. The game doesnt run. Just a black not responding window. Tried a manual and automatic installation. When started game there was window about auto update, i clicked "Yes".
Version 1.0.2.
Windows 11.

![Screenshot 2024-01-03 161504](https://github.com/TeamREPENTOGON/REPENTOGON/assets/47296483/5ffe0ee3-048d-402a-bb5d-21b705f706d4)

**Comment by epfly6** [comment]
Go to games folder -> try set CheckForUpdates = 0

**Comment by RainyNyte** [comment]
having a similar problem, the window asking about autoupdates freezes and stops responding, first time trying to use repentagon and I temporarily removed all other mods to see if there were just too many and it was slowing the process down. I don't have a dsound.ini file because it never gets far enough to generate it
