### ISSUE TITLE
Custom Challenges cannot be locked by custom achievements

### ISSUE THREAD

**Issue by SoraUltimateProgrammer** [TeamREPENTOGON/REPENTOGON#237]
I've looked around in the docs, and it doesn't look like there's any changes to challenges.xml to lock challenges behind custom achievements (by name), currently only supporting id instead.

**Comment by jsgnextortex** [comment]
They cannot be locked by vanilla achievements either, correct me if I'm wrong but this attribute seems ignored for custom challenges entirely by the game. It does sound like something we could eventually support tho, but we would need to see how to properly hide acchievements from the modded achievements menu...tbh, I dont like that menu at all so this may eventually come when we get to touching this one up.

**Comment by SoraUltimateProgrammer** [comment]
<img width="726" alt="image" src="https://github.com/TeamREPENTOGON/REPENTOGON/assets/26150648/8f368eb6-ae18-4bc1-b7e7-bbb7f33650db">

Can confirm that the attribute doesn't seem to work even with vanilla achievements (although it does exist, it seems to do nothing(?)

**Comment by jsgnextortex** [comment]
Well, vanilla challenges do use it and it is on the xml so ofc its going to be in the docs.
Anyway, the reason why theya re not hiding is because the modded challenges menu is ass and doesnt even have the ability to hide stuff normally. I'll label this and consider it planned....now when you'll se it?, I dunno, probably when we get to the challenge menu stuff.

**Comment by jsgnextortex** [comment]
already implemented, forgot to close
