### ISSUE TITLE
ModCallbacks.MC_GET_SHOP_ITEM_PRICE should have a price argument

### ISSUE THREAD

**Issue by Foks256** [TeamREPENTOGON/REPENTOGON#284]
ModCallbacks.MC_GET_SHOP_ITEM_PRICE currently doesn't have a price argument you can check for, which makes it quite hard to tell Devil Deal Prices and normal Shop Prices apart.

**Comment by dpower12** [comment]
I'm going to quote what connor said about the issue:

> The callback could probably run post-style (ie, after the internal code) and provide the price that the game chose (so that for example you could see it being negative for devil deals etc)
Right now it runs pre-style so it doesn't know what the game is gonna do
pre and post could be seperate callbacks I suppose, though there isn't really a difference between returning a value pre or post, because either way you override what the game was gonna do

Having the price as an optional arg could make this callback great for custom prices
but without a price argument it's very limited in its uses
