### ISSUE TITLE
MC_PRE/POST_PAUSE_SCREEN_RENDER should have third arg PauseOptions

### ISSUE THREAD

**Issue by Gemboat** [TeamREPENTOGON/REPENTOGON#300]
When in the options menu, the PAUSE_SCREEN_RENDER callbacks continue to trigger as expected. But the Sprite args are no longer relevant, and are not rendered on-screen.
I suspect there is a third Sprite object that is used for that case, and this should be provided in the callbacks.

**Comment by jsgnextortex** [comment]
The options menu is a completely different menu unrelated to the pause menu, it just so happens that the pause menu leads into it (but so does the main menu, its the same menu)

**Comment by Gemboat** [comment]
Ah, understood.
Is there a way to get the Sprite object of the menu, then? Even if you meant that it's literally the same, OptionsMenu can't be accessed while in-run, and it doesn't have its own callback to use instead.
And given that you'd only want to use it while PAUSE_SCREEN_RENDER is already running...

**Comment by jsgnextortex** [comment]
PAUSE_SCREEN_RENDER still runs because the menu is still open....but menu_options:Render() is called inside of it, lol.
Anyway, OptionsMenu is what you want, I just changed it so the OptionsMenu stuff is available for the pause menu instance of it too on 1.0.6, so you'll be able to get and manipulate optionsmenu stuff from the pause menu too. I'm not super sure a callback is needed, since, as you say, the pause one still runs and the options one renders on the same call.
