### ISSUE TITLE
Setting coinvalue xml attribute or returning something in MC_PICKUP_GET_COIN_VALUE breaks with entities that can pick up coins (like Bum Friend)

### ISSUE THREAD

**Issue by Foks256** [TeamREPENTOGON/REPENTOGON#334]

**Comment by ConnorForan** [comment]
The actual nature of this issue was that entities like bum friend, ultra greed, bumbino etc did not actually interact with the callback, the already-fixed GetCoinValue function, or the coinvalue XML attribute -at all-. They were already broken, and stayed broken because they did not actually ever call the GetCoinValue function that was previously fixed/hooked into our xmldata.

Fixed in https://github.com/TeamREPENTOGON/REPENTOGON/commit/202b71be07db4c9fc24609597ca6d0664bc3243b via individual patches
