### ISSUE TITLE
MC_GET_FOLLOWER_PRIORITY callback freezes the game

### ISSUE THREAD

**Issue by Foks256** [TeamREPENTOGON/REPENTOGON#342]
When setting a follower priority in this callback, giving yourself a custom familiar that uses this callback has no issue, however, if you had a familiar beforehand (like brother bobby) the game freezes after you add the custom familiar.

**Comment by ConnorForan** [comment]
- Follower familiars use their Parent/Child to form the "chain". The familiar at the front of the chain has NULL as its parent. FollowParent etc seems to just follow the Player if Parent is NULL.
- **The game can lock up if a follower has itself or a prior familiar in the chain as its Parent**, due to the game getting stuck in an infinite loop trying to follow the chain (such as in TryAimAtMarkedTarget, AddToFollowers, probably more). If the infinite loop isn't triggered, the chain will stop moving due to following itself.
- AddToFollowers tries to avoid adding the same familiar to the chain twice, by checking if the familiar has the IsFollower boolean and its Parent is already a familiar or player... EXCEPT, as I pointed out before, the front of the chain has a NULL Parent, not a player!!
  - Therefore, if AddToFollowers is called on the familiar at the front of the chain, the aforementioned safety check will pass and the game will attempt to place it into the chain again. Depending on FollowerPriority, it may attempt to place this "new" familiar at the second-to-front position... oops, the familiar is now parented to itself! Cue bug.
- During familiar Init, the game sets the IsFollower boolean on certain familiars (hardcoded/inlined, obviously), then later calls AddToFollowers if the IsFollower boolean is set. Notably this happens after MC_FAMILIAR_INIT, where mods often call AddToFollowers, which also sets the boolean, so the game will afterwards see IsFollower is set and call AddToFollowers a second time.
- The MC_GET_FOLLOWER_PRIORITY callback made the bug more likely to occur, since modded familiars are no longer relegated to the back of the line.

So, turns out the correct way to initialize a follower familiar was to set `fam.IsFollower = true` on init, and NOT to call AddToFollowers! The game would do it for you.

However, I hooked a safety check into AddToFollowers in https://github.com/TeamREPENTOGON/REPENTOGON/commit/48ee23a134793571489ed758524622207d0d951f to skip calls on the familiar already at the front of the chain, which will avoid the bug, so with that calling AddToFollowers on init will be safe and won't lead to duplicate insertions.
