### ISSUE TITLE
MC_POST__CHAMPION_GOO_REGEN(_, npc)

### ISSUE THREAD

**Issue by guwahavel** [TeamREPENTOGON/REPENTOGON#345]
EntityType optional parameter, would run when a dark red champion regenerates out of goo form

**Comment by ConnorForan** [comment]
Added MC_POST_NPC_DARK_RED_CHAMPION_REGEN in https://github.com/TeamREPENTOGON/REPENTOGON/commit/80ad000c54af7400eae775b01877517063640c7b

**Comment by guwahavel** [comment]
Could ChampionRegenTimer be exposed also?

**Comment by guwahavel** [comment]
Yeah I think a getter and setter would be useful even if niche, you can always use render or something if you really want to modify it during the state.

**Comment by ConnorForan** [comment]
The code for this champion is odd

The SpriteScale of the entity is halved if the timer is 2~5 or 81~85, and doubled if the timer is 6~9 or 86~90

In practice this means the scale of the entity always ends up unchanged in the end, but a mod messing with the timer would inevitably mess up the scale of the entity due to this behavior

Also, setting the timer to a non-zero value seems to just turn off the AI for an enemy who is not this champion type. Setting the timer on a dark red champion works as normal, though the anm2 for the goo pile is only loaded on one particular frame (5 I think?) so you could make it skip that.

Still not strictly opposed to exposing a setter, but wanted to voice some of the potential oddities I noticed already

**Comment by guwahavel** [comment]
I imagine the SpriteScale changing is for the shrinking/growing effect it has when turning into/out of the goo, seems pretty hardcoded. Knowing its like this I think it'd be ok if it was just a getter then.

**Comment by ConnorForan** [comment]
added `npc:GetDarkRedChampionRegenTimer()` in https://github.com/TeamREPENTOGON/REPENTOGON/commit/6d01a466d566c6d30a60cf6dffdd2cc1397b700a
