### ISSUE TITLE
Proper documentation and support for BlendMode of LayerState

### ISSUE THREAD

**Issue by guwahavel** [TeamREPENTOGON/REPENTOGON#347]
Despite being a very alluring and potentially useful feature it is not currently in a state which is intuitive or easy to apply.

**Comment by namishere** [comment]
This still needs plenty of additional research, but I've updated the docs to better reflect current knowledge with 25cd8f6.

**Comment by namishere** [comment]
Reminder to self to update docs with newly known [to me] .anm2 Layer node's BlendMode attribute.

**Comment by namishere** [comment]
I've decided against documenting this for the time being, as it seems the game is manually replacing the blend modes for all uses of this attribute (I wonder if there's some jank going on that requires this attribute to be set before manually correcting it?). However, I've gone through and documented nonstandard blend modes, as well as a decent guess as to what the `Flag[x]` variables are meant to be.

**Comment by namishere** [comment]
Update on this: BlendMode has recieved proper names for its modes and variables, enums for them, a link to documentation on glBlendFuncSeparate, and an expanded SetMode with new types. I potentially have someone working on an ingame demonstration mod, and it would be good to have a more indepth tutorial on how to use it (as I'm still not entirely sure how it all works), but I'm otherwise much happier with the state of the page and BlendMode itself.
