### ISSUE TITLE
(Potential Bug) MC_PRE_PLAYER_RENDER not flickering when player takes damage

### ISSUE THREAD

**Issue by Lunastela** [TeamREPENTOGON/REPENTOGON#383]
Title says it all. If this is not a bug, functionality to mirror that of MC_POST_PLAYER_RENDER (which does flicker when the player is taking damage) would be great. Thanks, again!

**Comment by Lunastela** [comment]
For anyone also in need of this functionality, here's a temporary fix:
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/142154042/60b06ec5-5f1c-4579-b0ba-5b6e18f8edc3)

**Comment by jsgnextortex** [comment]
The logic for the flicker happens inside of the player:render routine, so theres no way to know if it will flicker without calculating and evaluating everything twice, so just use your method. The reason why post is called in the way it is...is because its a friggin lie, it is not called after the whole player render has been resolved but rather inside of it, the post callback (which is a vanilla one) is actually called SOMETIMES after the sprite is rendered (some things like player trails, for example, wont trigger it on their own)
