### ISSUE TITLE
Custom Characters not appearing in Character Select and Major Fps Drop 

### ISSUE THREAD

**Issue by GalaxyHunterENT** [TeamREPENTOGON/REPENTOGON#384]
The custom Characters dont show up when launched with repentogon and the fps drops for no reason at all with it installed

**Comment by jsgnextortex** [comment]
When you mean not appearing, you mean not selectable or they are invisible?

**Comment by GalaxyHunterENT** [comment]
they are invisible in the character select screen  

also i found another thing when launching without repentogon your health bar is invisble

**Comment by GalaxyHunterENT** [comment]
and fps a run without repentogon runs normally but with repentogon that fps is cut in half and drops even more in large rooms and rooms with tons of enemies

**Comment by jsgnextortex** [comment]
If you have issues when launching without repentogon then it means those issues are unrelated to repentogon....I'd suggest going through your modlist and try to pinpoint which mod is causing the issue instead of trying to force a solution through this issue on something thats potentially not even on us. If you do find the root cause of this (by enabling/disabling mods) please let us know. 
About the "fps cut in half", I will assume you are exaggerating there, but depending on what setup you have and what mods you have on it could hold some truth in therms of having a mild perf impact, we will be addressing some of these in 108. Still, if you got to this point, I assume you have way more mods than the game can handle and a lot of them may be causing errors.

**Comment by GalaxyHunterENT** [comment]
I'm not exaggerating the fps cut without repentogon it runs between 50 - 60 fps with repentogon it runs 22-30 fps. I've also disabled some of my bigger mods and still get the fps cut.

and I have go through all my mods to see if it was one of them but this only happens when repentogon active.

and I'm not trying to force a solution I'm just stating what's happening when I use repentogon,

**Comment by jsgnextortex** [comment]
try with the new 1.0.8 version and let us know if you notice any improvements...still, I assume your fps may be lower than vanilla still because it gives me the impression that your game must be erroring like hell (which may affect perf with repentogon a little more since we do some extra stuff with errors). You are not expected to ignore errors and call it a day but rather address them, report them and disable the mods that error if they are not fixe, I'd suggest checking your console and logs for errrors and seeing if you notice the root cause of them to take proper action.

**Comment by GalaxyHunterENT** [comment]
The update is making the game crash on the main menu even when removing all my mods.  Though I think Its just my PC being Stupid.   Just thought I'd Let y'all know.
