### ISSUE TITLE
StartNewGame seed option lets you bypass disabled achievements

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#482]
Normally, setting a seed via the menu or the "seed" command will cause the "achievements disabled" icon to show.

Setting a seed via Isaac.StartNewGame appears to bypass this.

I also noticed that you can set a seed for challenges using this method. Normally, the "seed" command doesn't work in challenges.

**Comment by jsgnextortex** [comment]
Is this really about "cheating"?, I want to give you the benefit of doubt but removing features just because you can cheat by using lua (in the case of challenges) seems flat out stupid, as theres an infinite amount of ways to cheat in lua and repentogon even adds the ability to flat out unlock achievements....is there something I'm missing?

**Comment by laceous** [comment]
It just seemed inconsistent to me, so I figured I'd report it.

**Comment by jsgnextortex** [comment]
The game also sets a seed when a run starts and the achievements are not locked then(otherwise they would always be locked), you seem to be thinking as this functionality as a shortcut to the seeds menu when its not that....its simply exposing game functionality, if you want the ability to lock achieveemnts then that would be a valid request, but it has nothing to do with setting a seed.

**Comment by jsgnextortex** [comment]
Also, as a closing note, being able to cheat is not an acceptable point of discussion when talking about api features, the moment you have access to the code you stop being a player and start becoming a developer, so these sort of things no longer apply. If your fear is people making cheats, they can already do that with the vanilla api.
