### ISSUE TITLE
After the latest Isaac update the game constantly crashes

### ISSUE THREAD

**Issue by marto05** [TeamREPENTOGON/REPENTOGON#493]
After the latest update every time I try to start a run while running Repentogon the game freezes and crashes

**Comment by namishere** [comment]
please post game version, as defined by `Documents/My Games/Binding of Isaac Repentance/log.txt` in a line like `[INFO] - Binding of Isaac: Repentance v1.[xxx]`

**Comment by marto05** [comment]
[INFO] - Binding of Isaac: Repentance v1.7.9b.J835

**Comment by jsgnextortex** [comment]
You say "After the latest Isaac update", what do you mean by this?, Isaac hasnt recieved an update in years and it hasnt recieved an update since Repentogon came out, which was this "latest update" you speak of that broke repentogon?. The version you claim to have is the correct one btw, Im just confused about your wording here.

**Comment by marto05** [comment]
I made a mistake in my wording. I downloaded a mod, and Steam considered it an update, which confused me.

**Comment by marto05** [comment]
Still even after deleting said mod the game keeps crashing

**Comment by jsgnextortex** [comment]
Sadly thats not enough info for us to know what could be going on, please provide your Documents/My Games/Binding of Isaac Repentance/log.txt

**Comment by marto05** [comment]
It seems like I fixed it by redownloading the game and then REPENTOGON
