### ISSUE TITLE
"ActiveSlot cannot be higher than 3" in EntityPlayer:GetActiveItemDesc()

### ISSUE THREAD

**Issue by RealexTea** [TeamREPENTOGON/REPENTOGON#524]
It literally can wtf. My mod uses fourth (kinda secret but existing and stable working) slot to make items like Urn of Souls and Vade Retro work properly. Please remove this stupid artificial restriction.

**Comment by epfly6** [comment]
The game only reserves 4 active item slots (primary, secondary with The Schoolbag, pocket active item and temporary pocket active item). Goind out of bounds might cause issues as crashes and etc.

**Comment by jerbmega** [comment]
> Please remove this stupid artificial restriction.

The restriction is neither artificial nor stupid. We will not remove checks that prevent arbitrary reads and writes to undefined and unrelated memory regions. They're in place for a reason.

I don't care if it *appears* to work. The reality is, your "fourth slot" is writing outside of the region in memory the game reserves for active slots. This will not be fixed because there is nothing to fix here, and the check is working as intended.
