### ISSUE TITLE
Save Data Sync Issue

### ISSUE THREAD

**Issue by EminentEmily** [TeamREPENTOGON/REPENTOGON#547]
Hello:

I'm using the installer version of REPENTOGON, and I play Binding of Isaac on both my desktop and laptop computers. I've noticed after installing that save data is no longer syncing correctly. I'm not sure if this is an issue in the Steam Workshop version.

**Comment by jsgnextortex** [comment]
This is almost certainly unrelated to repentogon and more so related to Steam Cloud issues. I'd double check that steamcloud is enabled on both sides....otherwise, if you still believe this to be a repentogon issue, for some reason, can you elaborate on what you mean when you say that it doesnt "sync correctly"?, like does it not sync at all?, does it sync only sometimes?, does it error?

**Comment by namishere** [comment]
Closed because of inactivity
