### ISSUE TITLE
[macOS compatibility] Game won't open file not found

### ISSUE THREAD

**Issue by skroow** [TeamREPENTOGON/REPENTOGON#563]
I'm on macOS using wine. Installed REPENTOGON using the exe and manually same issue. After starting the game a popup appears saying "File not found"

<img width="148" alt="Screenshot 2024-10-08 at 18 13 04" src="https://github.com/user-attachments/assets/9cde1c7b-3de1-4f70-8afb-c5bb6e7215bb">
<img width="632" alt="Screenshot 2024-10-08 at 18 13 28" src="https://github.com/user-attachments/assets/cc28453f-c8bc-499c-836d-28d436844b93">
<img width="838" alt="Screenshot 2024-10-08 at 18 13 44" src="https://github.com/user-attachments/assets/dba825d7-39ab-449e-a91a-6fffc03217f9">
<img width="423" alt="Screenshot 2024-10-08 at 18 14 15" src="https://github.com/user-attachments/assets/6f930592-0ce4-4d1c-a23a-6357fbbde595">

**Comment by skroow** [comment]
But while trying to run it manually using "WINEDLLOVERRIDES="dsound=n,b" wine isaac-ng.exe" form the terminal the game starts REPENTOGON load for 1 sec I can hear the game and then it crushes.

**Comment by Tenoen** [comment]
I have the exact same problem currently.

**Comment by jerbmega** [comment]
This is due to our integration of ImGui for the new console in OpenGL 3 mode whereas Isaac technically only needs GL 2. JSG and I have both tried switching ImGui to OpenGL 2, but ImGui fails to render when doing so. Unfortunately none of us have macOS hardware to test with.

If you're on an Apple Silicon mac, I suspect Asahi Fedora Remix will run REPENTOGON with no problem, otherwise you'll have to use Boot Camp. I'll leave this issue open for if the situation changes.

**Comment by jerbmega** [comment]
This should be resolved by a9fd334.
