### ISSUE TITLE
level:FindValidRoomPlacementLocations does not work in MC_POST_LEVEL_LAYOUT_GENERATED

### ISSUE THREAD

**Issue by dpower12** [TeamREPENTOGON/REPENTOGON#586]
it seems that the function `level:FindValidRoomPlacementLocations` does not work properly when used in the callback `MC_POST_LEVEL_LAYOUT_GENERATED` as it will always return 0 valid rooms
I can use `MC_POST_NEW_LEVEL` instead to make it work, but that causes to add additional rooms when it shouldn't, as these rooms are supposed to be added only when a new layout is generated.

is this intended behavior?

**Comment by ConnorForan** [comment]
These level functions are intended to add new rooms onto existing floors, similarly to red key, but more flexible. They are not part of LevelGenerator for a reason, and are not intended for use in the middle of level generation.

The "layout" referred to in `MC_POST_LEVEL_LAYOUT_GENERATED` means that the level generator has created the shape of the floor, but has not actually placed any actual roomconfig layouts yet. Therefore `FindValidRoomPlacementLocations` cannot find existing rooms to attach to.

Can you elaborate on "I can use MC_POST_NEW_LEVEL instead to make it work, but that causes to add additional rooms when it shouldn't", because I am not aware of any reason why MC_POST_NEW_LEVEL would cause such a problem. If anything, that is the exactly correct callback to be using these functions on.

**Comment by dpower12** [comment]
I was under the assumption that new rooms that are supposed to be part of the inital floor generation should have been added in `MC_POST_LEVEL_LAYOUT_GENERATED` to avoid generation issues, the first example when I made the post was using forget me now thinking that forget me now doesn't trigger another `MC_POST_LEVEL_LAYOUT_GENERATED`. after testing with `MC_POST_NEW_LEVEL` I couldn't find any of the potential issues of my initial statement, so I'll mark this issue as resolved, thanks for the explanation.
